name: "Build (Java)"

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:
  release:
    types: [ released, prereleased ]

jobs:
  build:
    uses: xpdustry/.github/.github/workflows/build-java.yaml@master
    with:
      java_version: 17
      artifacts_path: build/tmp/release/*.jar
      version_file: plugin.json
      version_file_kind: mindustry-mod
      publish_maven: false
      build_command: "release"
    secrets: "inherit"
